"""
Generate the Metameric Memory Engine long-form essay on the local fleet ($0).

Five phases of the 21-module loop, ~1,700 words each, written sequentially
(one model loaded at a time — 8GB VRAM ceiling). Tries the QB (gemma4:12b)
first, falls back to gemma4-aggressive:e4b per phase. Output assembles into
a single markdown draft for the NouGenSite blog.
"""
import json
import os
import sys
import time
import urllib.request
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

OLLAMA = "http://127.0.0.1:11434/api/generate"
MODELS = ["gemma4:12b", "gemma4-aggressive:e4b"]
# Output path is configurable (no hardcoded author path in a public repo).
# METAMERIC_LONGFORM_OUT overrides directly; otherwise derive from WATCHTOWER_ROOT
# (default: ~/Watchtower).
_WT_ROOT = Path(os.environ.get("WATCHTOWER_ROOT", str(Path.home() / "Watchtower")))
OUT = os.environ.get(
    "METAMERIC_LONGFORM_OUT",
    str(_WT_ROOT / "NouGen" / "NouGenSite" / "app" / "blog" / "metameric-engine-longform.md"),
)

PHASES = [
    ("Phase 1: The Reconnaissance (Discovery & Parsing)",
     ["Metamers", "Activate Orchestration", "Deep Grep Latent Structure",
      "Surface Leverage"]),
    ("Phase 2: The Extraction (Ingestion & Normalization)",
     ["Extract Invariants", "Copy Successful Topology", "Transpose Patterns",
      "Combine Compatible Systems"]),
    ("Phase 3: The Substrate (Storage & Hardening)",
     ["Synthesize Coherent Signal", "Integrate Constraints",
      "Transform Architecture", "Refactor Complexity"]),
    ("Phase 4: The Dream State (Evolution & Recall)",
     ["Compress Noise", "Expand Solution Space", "Remix Viable Patterns",
      "Invert Assumptions", "Reverse-Engineer Intent",
      "Reconstruct Coherence", "Stabilize Reasoning"]),
    ("Phase 5: The Loop (Convergence)",
     ["Iterate Recursively", "Orchestrate Convergence"]),
]

CONTEXT = (
    "NouGenShards is a local-first memory engine for AI agents built by Dave "
    "Meralus (Who Visions LLC / NouGenAi): SQLite shard storage across a 9-DB "
    "cluster, FTS5/BM25 plus vector retrieval fused by Bayesian scoring, "
    "utility feedback (mark_utility), temporal grounding (every recalled "
    "memory carries local wall-clock time and relative age), a graph mesh "
    "linking shards, and a named agent fleet (Sharder, Remember, Kronos, "
    "DavOs, Sol-Ai, quarterback NouGen) running on local Ollama models. "
    "Origin: November 2025 frustration with Vertex AI / BigQuery / Firebase "
    "RAG costs and latency; December 2025 bulk ingestion (6,216 shards in one "
    "day); by June 2026 a 33,000+ shard vault, a verified TypeScript port, "
    "and a public GitHub repo. Motif: 'Anghkooey' means remember — every "
    "stateless AI session is a reincarnation; memory breaks the cycle.")


def generate(model, prompt, timeout=900):
    body = json.dumps({"model": model, "prompt": prompt, "stream": False,
                       "options": {"num_ctx": 8192, "temperature": 0.75,
                                   "num_predict": 3500}}).encode()
    req = urllib.request.Request(OLLAMA, body,
                                 {"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read())["response"]


def main():
    sections = ["# The Metameric Memory Engine: A 21-Module Anatomy of "
                "Machine Memory\n",
                "> Long-form draft generated by the local NouGen fleet, "
                "reviewed by the Coach. $0 cloud cost.\n"]
    for title, modules in PHASES:
        prompt = (
            f"{CONTEXT}\n\nWrite the section '{title}' of a long-form "
            f"technical essay titled 'The Metameric Memory Engine'. Cover "
            f"these modules in order, each with its own subsection: "
            f"{', '.join(modules)}. For each module explain what it means in "
            f"the NouGenShards architecture, with concrete grounding in the "
            f"system described above. Write 1,500-1,800 words for this "
            f"section. Markdown, ## for the section title, ### for modules. "
            f"Technical but vivid; no bullet-point filler; complete prose.")
        section = None
        for model in MODELS:
            try:
                t0 = time.time()
                section = generate(model, prompt)
                print(f"[{title}] {model} OK, {len(section.split())} words, "
                      f"{time.time() - t0:.0f}s", flush=True)
                break
            except Exception as exc:  # noqa: BLE001 — try next model
                print(f"[{title}] {model} failed: {exc}", flush=True)
        sections.append(section or f"## {title}\n\n*(generation failed — "
                                   f"regenerate this phase)*")
    text = "\n\n".join(sections)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"DONE: {len(text.split())} words -> {OUT}", flush=True)


if __name__ == "__main__":
    main()
